version: '3.1'
services:
  stats-server:
    build:
      context: ./ewm-stats-service/stats-service
      dockerfile: Dockerfile
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=stats_service
      - POSTGRES_USER=statsUser
      - POSTGRES_PASSWORD=p#12H8sd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U statsUser -d stats_service" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ewm-service:
    build:
      context: ./ewm-main-service
      dockerfile: Dockerfile
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      - EWM_STATS_SERVICE_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewmUser
      - POSTGRES_PASSWORD=f#57Hx9jz
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ewmUser -d ewm" ]
      interval: 10s
      timeout: 5s
      retries: 5