drop table if exists hits;

create table if not exists hits (
    hit_id bigint generated by default as identity,
    hit_app varchar(128) not null,
    hit_uri varchar(255) not null,
    hit_user_ip varchar(15) not null,
    hit_created timestamp without time zone not null,
    constraint pk_hit_id primary key (hit_id)
);